name: eosc
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.*
  - pandas==1.5.3
  - pip
  - pip:
    - ipywidgets<8  # required for display. Remove if you are not using notebook
    - matplotlib==3.7.1
    - jupyter==1.0.0
    - requests==2.31.0
